fix: Arrumando o .yaml para echo não mascarar o erro

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,7 +34,10 @@ jobs:
 
           - name: Analyze Jupyter Notebooks
             run: |
-              nbstripout --verify Aula2/explorer.ipynb || echo "Jupyter Notebook contains output cells. Please remove them before committing."
+                nbstripout --verify Aula2/explorer.ipynb || {
+                echo "::error file=Aula2/explorer.ipynb::Notebook contém células com output. Remova antes de commitar."
+                exit 1
+                }
 
           - name: Instalar Ruff (Linter)
             run: pip install ruff 
